# Generated by Django 3.2.13 on 2022-06-13 13:03

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/static/', location=pathlib.PureWindowsPath('D:/it/Projects/Python/2022/pasta-la-vista-baby/WebsiteApp/static')), upload_to='images/food/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=160)),
                ('phone_number', models.CharField(max_length=20)),
                ('delivery_type', models.CharField(choices=[('1', 'Delivery'), ('2', 'Pickup')], max_length=1)),
                ('delivery_address', models.CharField(blank=True, max_length=160)),
                ('payment_type', models.CharField(choices=[('1', 'Cash'), ('2', 'Card')], max_length=1)),
                ('amount_of_tools', models.IntegerField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('order_time', models.TimeField(auto_now_add=True)),
                ('food_id_list', models.JSONField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
