# Generated by Django 3.2.13 on 2022-06-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='food_id_list',
            field=models.JSONField(default=list),
        ),
    ]
