# Generated by Django 4.0.5 on 2022-06-28 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteApp', '0002_alter_ordermodel_food_id_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodel',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
