# Generated by Django 4.0.5 on 2022-06-29 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteApp', '0003_foodcategory_foodmodel_in_stock_foodmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('phone_number', models.CharField(max_length=20)),
                ('reservation_time', models.DateTimeField(auto_now_add=True)),
                ('reserved_for', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebsiteApp.foodcategory'),
        ),
    ]
